//categories types
export const GET_CONFIGURATION = "GET_CONFIGURATION";
export const START_FETCHING_CONFIGURATION = "START_FETCHING_CONFIGURATION";

//paging previous and next
export const PREVIOUS = "PREVIOUS";
export const NEXT = "NEXT";

//handle all input control change
export const HANDLE_CHANGE="HANDLE_CHANGE";

//add server groups and servers
export const ADD_SERVERGROUPS_SERVERS="ADD_SERVERGROUPS_SERVERS";

export const HANDLE_SERVERGROUP_CHANGE="HANDLE_SERVERGROUP_CHANGE";
export const REMOVE_SERVERGROUP="REMOVE_SERVERGROUP";

export const HANDLE_SERVER_CHANGE="HANDLE_SERVER_CHANGE";
export const REMOVE_SERVER="REMOVE_SERVER";

export const SELECT_AVAILABLE_SOFWARE="SELECT_AVAILABLE_SOFWARE";
export const SELECT_CHOOSEN_SOFTWARE="SELECT_CHOOSEN_SOFTWARE";

export const SOFTWARE_ITEMS_MOVE_RIGHT="SOFTWARE_ITEMS_MOVE_RIGHT";
export const SOFTWARE_ITEMS_MOVE_ALL_RIGHT="SOFTWARE_ITEMS_MOVE_ALL_RIGHT";

export const SOFTWARE_ITEMS_MOVE_LEFT="SOFTWARE_ITEMS_MOVE_LEFT";
export const SOFTWARE_ITEMS_MOVE_ALL_LEFT="SOFTWARE_ITEMS_MOVE_ALL_LEFT";

export const START_SCRIPT_EXECUTION="START_SCRIPT_EXECUTION";
export const SCRIPT_EXECUTION_STATUS="SCRIPT_EXECUTION_STATUS";

